pipeline {
    agent any

    stages {
        stage('Build WAR') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t java-tomcat-app .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 8084:8080 --name tomcat-app java-tomcat-app'
            }
        }
    }

    post {
        failure {
            echo "❌ Build or Deploy Failed"
        }
        success {
            echo "✅ Deployment Successful"
        }
    }
}
